// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.2
// source: genai/genai.proto

package genai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Chunk content
type Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meaning string `protobuf:"bytes,1,opt,name=meaning,proto3" json:"meaning,omitempty"`
	Text    string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genai_genai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_genai_genai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_genai_genai_proto_rawDescGZIP(), []int{0}
}

func (x *Chunk) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *Chunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Text Split request message
type TextSplitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *TextSplitRequest) Reset() {
	*x = TextSplitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genai_genai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextSplitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextSplitRequest) ProtoMessage() {}

func (x *TextSplitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genai_genai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextSplitRequest.ProtoReflect.Descriptor instead.
func (*TextSplitRequest) Descriptor() ([]byte, []int) {
	return file_genai_genai_proto_rawDescGZIP(), []int{1}
}

func (x *TextSplitRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Text Split Response message
type TextSplitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []*Chunk `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
}

func (x *TextSplitResponse) Reset() {
	*x = TextSplitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genai_genai_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextSplitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextSplitResponse) ProtoMessage() {}

func (x *TextSplitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genai_genai_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextSplitResponse.ProtoReflect.Descriptor instead.
func (*TextSplitResponse) Descriptor() ([]byte, []int) {
	return file_genai_genai_proto_rawDescGZIP(), []int{2}
}

func (x *TextSplitResponse) GetContent() []*Chunk {
	if x != nil {
		return x.Content
	}
	return nil
}

// Q&A request message
type QARequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question string `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Context  string `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
}

func (x *QARequest) Reset() {
	*x = QARequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genai_genai_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QARequest) ProtoMessage() {}

func (x *QARequest) ProtoReflect() protoreflect.Message {
	mi := &file_genai_genai_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QARequest.ProtoReflect.Descriptor instead.
func (*QARequest) Descriptor() ([]byte, []int) {
	return file_genai_genai_proto_rawDescGZIP(), []int{3}
}

func (x *QARequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *QARequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

// Q&A response message
type QAResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *QAResponse) Reset() {
	*x = QAResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genai_genai_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QAResponse) ProtoMessage() {}

func (x *QAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genai_genai_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QAResponse.ProtoReflect.Descriptor instead.
func (*QAResponse) Descriptor() ([]byte, []int) {
	return file_genai_genai_proto_rawDescGZIP(), []int{4}
}

func (x *QAResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

// MC generate request message
type MCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context string `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
}

func (x *MCRequest) Reset() {
	*x = MCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genai_genai_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCRequest) ProtoMessage() {}

func (x *MCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genai_genai_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCRequest.ProtoReflect.Descriptor instead.
func (*MCRequest) Descriptor() ([]byte, []int) {
	return file_genai_genai_proto_rawDescGZIP(), []int{5}
}

func (x *MCRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

// MC generate response message
type MCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question      string   `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answers       []string `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	CorrectAnswer string   `protobuf:"bytes,3,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"`
	Explanation   string   `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
}

func (x *MCResponse) Reset() {
	*x = MCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genai_genai_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCResponse) ProtoMessage() {}

func (x *MCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genai_genai_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCResponse.ProtoReflect.Descriptor instead.
func (*MCResponse) Descriptor() ([]byte, []int) {
	return file_genai_genai_proto_rawDescGZIP(), []int{6}
}

func (x *MCResponse) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *MCResponse) GetAnswers() []string {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *MCResponse) GetCorrectAnswer() string {
	if x != nil {
		return x.CorrectAnswer
	}
	return ""
}

func (x *MCResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

var File_genai_genai_proto protoreflect.FileDescriptor

var file_genai_genai_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x65, 0x6e, 0x61, 0x69, 0x2f, 0x67, 0x65, 0x6e, 0x61, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x65, 0x6e, 0x61, 0x69, 0x22, 0x35, 0x0a, 0x05, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x2c, 0x0a, 0x10, 0x54, 0x65, 0x78, 0x74, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x3b, 0x0a, 0x11, 0x54, 0x65, 0x78, 0x74, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x65, 0x6e, 0x61, 0x69, 0x2e, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x41, 0x0a, 0x09,
	0x51, 0x41, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22,
	0x24, 0x0a, 0x0a, 0x51, 0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x25, 0x0a, 0x09, 0x4d, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x8b, 0x01, 0x0a,
	0x0a, 0x4d, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65,
	0x63, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x6c,
	0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65,
	0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xc2, 0x01, 0x0a, 0x0c, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x76, 0x65, 0x41, 0x49, 0x12, 0x40, 0x0a, 0x09, 0x54,
	0x65, 0x78, 0x74, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x12, 0x17, 0x2e, 0x67, 0x65, 0x6e, 0x61, 0x69,
	0x2e, 0x54, 0x65, 0x78, 0x74, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x67, 0x65, 0x6e, 0x61, 0x69, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x53, 0x70,
	0x6c, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a,
	0x0e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x77, 0x73, 0x65, 0x72, 0x12,
	0x10, 0x2e, 0x67, 0x65, 0x6e, 0x61, 0x69, 0x2e, 0x51, 0x41, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x67, 0x65, 0x6e, 0x61, 0x69, 0x2e, 0x51, 0x41, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x65, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x10, 0x2e, 0x67, 0x65, 0x6e, 0x61, 0x69,
	0x2e, 0x4d, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x67, 0x65, 0x6e,
	0x61, 0x69, 0x2e, 0x4d, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0f, 0x5a, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x67, 0x65, 0x6e, 0x61, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_genai_genai_proto_rawDescOnce sync.Once
	file_genai_genai_proto_rawDescData = file_genai_genai_proto_rawDesc
)

func file_genai_genai_proto_rawDescGZIP() []byte {
	file_genai_genai_proto_rawDescOnce.Do(func() {
		file_genai_genai_proto_rawDescData = protoimpl.X.CompressGZIP(file_genai_genai_proto_rawDescData)
	})
	return file_genai_genai_proto_rawDescData
}

var file_genai_genai_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_genai_genai_proto_goTypes = []interface{}{
	(*Chunk)(nil),             // 0: genai.Chunk
	(*TextSplitRequest)(nil),  // 1: genai.TextSplitRequest
	(*TextSplitResponse)(nil), // 2: genai.TextSplitResponse
	(*QARequest)(nil),         // 3: genai.QARequest
	(*QAResponse)(nil),        // 4: genai.QAResponse
	(*MCRequest)(nil),         // 5: genai.MCRequest
	(*MCResponse)(nil),        // 6: genai.MCResponse
}
var file_genai_genai_proto_depIdxs = []int32{
	0, // 0: genai.TextSplitResponse.content:type_name -> genai.Chunk
	1, // 1: genai.GenerativeAI.TextSplit:input_type -> genai.TextSplitRequest
	3, // 2: genai.GenerativeAI.QuestionAnwser:input_type -> genai.QARequest
	5, // 3: genai.GenerativeAI.MultipleChoice:input_type -> genai.MCRequest
	2, // 4: genai.GenerativeAI.TextSplit:output_type -> genai.TextSplitResponse
	4, // 5: genai.GenerativeAI.QuestionAnwser:output_type -> genai.QAResponse
	6, // 6: genai.GenerativeAI.MultipleChoice:output_type -> genai.MCResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_genai_genai_proto_init() }
func file_genai_genai_proto_init() {
	if File_genai_genai_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_genai_genai_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_genai_genai_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextSplitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_genai_genai_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextSplitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_genai_genai_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QARequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_genai_genai_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QAResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_genai_genai_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_genai_genai_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_genai_genai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_genai_genai_proto_goTypes,
		DependencyIndexes: file_genai_genai_proto_depIdxs,
		MessageInfos:      file_genai_genai_proto_msgTypes,
	}.Build()
	File_genai_genai_proto = out.File
	file_genai_genai_proto_rawDesc = nil
	file_genai_genai_proto_goTypes = nil
	file_genai_genai_proto_depIdxs = nil
}
