# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genai.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgenai.proto\x12\x05genai\"&\n\x05\x43hunk\x12\x0f\n\x07meaning\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"#\n\x10TextSplitRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"2\n\x11TextSplitResponse\x12\x1d\n\x07\x63ontent\x18\x01 \x03(\x0b\x32\x0c.genai.Chunk\".\n\tQARequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\"\x1c\n\nQAResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"\x1c\n\tMCRequest\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t\"\\\n\nMCResponse\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0f\n\x07\x61nswers\x18\x02 \x03(\t\x12\x16\n\x0e\x63orrect_answer\x18\x03 \x01(\t\x12\x13\n\x0b\x65xplanation\x18\x04 \x01(\t2\xc2\x01\n\x0cGenerativeAI\x12@\n\tTextSplit\x12\x17.genai.TextSplitRequest\x1a\x18.genai.TextSplitResponse\"\x00\x12\x37\n\x0eQuestionAnwser\x12\x10.genai.QARequest\x1a\x11.genai.QAResponse\"\x00\x12\x37\n\x0eMultipleChoice\x12\x10.genai.MCRequest\x1a\x11.genai.MCResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genai_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHUNK']._serialized_start=22
  _globals['_CHUNK']._serialized_end=60
  _globals['_TEXTSPLITREQUEST']._serialized_start=62
  _globals['_TEXTSPLITREQUEST']._serialized_end=97
  _globals['_TEXTSPLITRESPONSE']._serialized_start=99
  _globals['_TEXTSPLITRESPONSE']._serialized_end=149
  _globals['_QAREQUEST']._serialized_start=151
  _globals['_QAREQUEST']._serialized_end=197
  _globals['_QARESPONSE']._serialized_start=199
  _globals['_QARESPONSE']._serialized_end=227
  _globals['_MCREQUEST']._serialized_start=229
  _globals['_MCREQUEST']._serialized_end=257
  _globals['_MCRESPONSE']._serialized_start=259
  _globals['_MCRESPONSE']._serialized_end=351
  _globals['_GENERATIVEAI']._serialized_start=354
  _globals['_GENERATIVEAI']._serialized_end=548
# @@protoc_insertion_point(module_scope)
